name: CMake

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependence
      run: brew install gperf cmake openssl

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --target install
      
    - name: Upload Target
      uses: actions/upload-artifact@master
      with:
        name: tdlib
        path: /
      
